# Site settings
title: Nishant Sharma
email: nishantsh2002@gmail.com
description: >-
  This is my personal website. I've put my projects/blogs/notes here.
  in your document head meta and in your feed.xml site description.
baseurl: "" # remove the "/" to prevent double slashes
url: "http://127.0.0.1:4000" # for local development
twitter_username: nishantsh2002
github_username: sevendaystoglory

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed 
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 
  - .gitignore
  - _site/

collections:
  posts:
    output: true
    permalink: _posts/:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: "_posts/blogs"
    values:
      category: blogs
  - scope:
      path: "_posts/til"
    values:
      category: til
  - scope:
      path: "_posts/projects"
    values:
      category: projects