# Site settings
title: Your Name
email: your-email@example.com
description: >-
  Write a description about your site here. This will appear 
  in your document head meta and in your feed.xml site description.
baseurl: ""
url: "https://yourusername.github.io"
twitter_username: yourusername
github_username: yourusername

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 